### PR TITLE
PR: modification of edit article page to fix unvisible content problem

### PR DESCRIPTION
**Pull request by creative2113**

### CODE REVIEW

**Comment by creative2113** [comment]
I have resolve the problem for edit page.
please check this code and give me a good review.

**Comment by creative2113** [comment]
hello, there.
I have fixed that problem.
please check that.
thx

**Comment by creative2113** [comment]
thanks again.

**Comment by shinevue** [comment]
Ok
Great

**Review by shinevue — APPROVED** [review]
Awesome

**Pull request merged**
