### PR TITLE
PR: change folder structure

### PR DESCRIPTION
**Pull request by chrisarnold3**

### CODE REVIEW

**Review by dragonsea0927 — APPROVED** [review]

**Review by goldsunshines — APPROVED** [review]
That was very necessary.

**Review by vadymtsaran — APPROVED** [review]

**Review by stanislavboik — APPROVED** [review]

**Review by richdev0724 — APPROVED** [review]

**Review by passionatedev724 — APPROVED** [review]

**Review by michaelmoyer7 — APPROVED** [review]

**Review by rostislavmiro — APPROVED** [review]

**Comment by felipedev418** [comment]
Yes. it is important

**Review by hotshinydev — APPROVED** [review]

**Review by myVos-dev — APPROVED** [review]
Yes, I am agree with you

**Comment by coinel7** [comment]
That's great

**Comment by BeautifulMoon211** [comment]
🥰

**Comment by BeautifulMoon211** [comment]
🥰

**Comment by BeautifulMoon211** [comment]
🥰

**Comment by BeautifulMoon211** [comment]
🥰

**Pull request merged**
