### PR TITLE
fix: fetch team members from github orgarnization

### PR DESCRIPTION
**Pull request by shinevue**

### CODE REVIEW

**Comment by 7CodeWizard** [comment]
Now, I can help you. Pls contact to me

**Review by techietrend — APPROVED** [review]
Creative idea.

**Review by popstar7 — APPROVED** [review]
Very good.
Let's go ahead.

**Review by silvershiny — COMMENTED** [review]
Thank you for your effort. 😊

**Review by silvershiny — APPROVED** [review]
Thank you for your effort. 😊

**Comment by creative2115** [comment]
handsome

**Review by creative2115 — APPROVED** [review]
awesome

**Review by goldsunshines — APPROVED** [review]
Me too

**Review by silvershiny — APPROVED** [review]
Please improve in detail

**Comment by 7CodeWizard** [comment]
Great!

**Comment by shinevue** [comment]
> Now, I can help you. Pls contact to me

Please visit discussion and register yourself.

**Pull request merged**
