### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by shinevue**

### CODE REVIEW

**Review by creative2113 — APPROVED** [review]
good
go ahead

**Review by joellake992 — APPROVED** [review]
Expect more wonderful update

**Review by techietrend — APPROVED** [review]
Good job, PM

**Comment by BlackGhost2693** [comment]
you are great.
I hope you are the best of luck

**Comment by creative2113** [comment]
Hello @BlackGhost2693 

please merge.
don't send me notification.

**Pull request merged**
