### PR TITLE
PR: remove the package-lock.json file for install yarn module

### PR DESCRIPTION
**Pull request by creative2113**
please check this and go ahead.
thanks

### CODE REVIEW

**Review by shinevue — APPROVED** [review]
Fantastic, awesome.
I look forward to your bid development.

**Review by techietrend — APPROVED** [review]
Great
You are the best developer.

**Review by joellake992 — APPROVED** [review]
Amazing work.

**Comment by gitMan-stack** [comment]
oh , I have learned a lot from this
Thanks

**Comment by Luis96920** [comment]
you are very passive and creative.

**Pull request merged**
