### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by popstar7**

### CODE REVIEW

**Review by shinevue — APPROVED** [review]
Yep, thank you

**Review by silvershiny — APPROVED** [review]
Good job, dear popstar

**Review by techietrend — APPROVED** [review]
Nice step

**Review by goldsunshines — APPROVED** [review]
Let's go, 👍

**Review by shiny7star — APPROVED** [review]
awesome

**Review by creative2113 — APPROVED** [review]
good

**Review by Johnhvy — APPROVED** [review]
I agree

**Review by BeautifulMoon211 — COMMENTED** [review]
Good!
Sincerely thank you for your continuous efforts.

**Comment by appleseed619** [comment]
I am a talented python expert.

**Comment by appleseed619** [comment]
I do my best for teammates.

**Pull request merged**
