### PR TITLE
PR: add shiny7star as a contributor.

### PR DESCRIPTION
**Pull request by shiny7star**

### CODE REVIEW

**Review by shinevue — APPROVED** [review]
Welcome

**Review by creative2113 — APPROVED** [review]
ok

**Comment by BlackGhost2693** [comment]
okay

**Review by popstar7 — APPROVED** [review]
Welcome

**Review by goldsunshines — APPROVED** [review]
Yeo, that's good

**Review by techietrend — APPROVED** [review]
ok

**Review by silvershiny — APPROVED** [review]
After that, please accept me too

**Pull request merged**
