### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by shinevue**

### CODE REVIEW

**Review by Johnhvy — APPROVED** [review]
Okay.
I agree

**Comment by BlackGhost2693** [comment]
okay
welcome

**Comment by gitMan-stack** [comment]
You are welcome

**Comment by creative2113** [comment]
looks good.

**Review by techietrend — APPROVED** [review]
Alright.
We need LICENSE.

**Review by joellake992 — APPROVED** [review]
You discovered important
I agree with you

**Review by pattboy-git — APPROVED** [review]
ok

**Pull request merged**
