### PR TITLE
PR: Improve teammate's table

### PR DESCRIPTION
**Pull request by shinevue**

### CODE REVIEW

**Review by creative2113 — APPROVED** [review]
very Good, Bro.

**Review by Johnhvy — APPROVED** [review]
Great.
I agree

**Review by purity111 — APPROVED** [review]
It's beautiful code.

**Review by purity111 — APPROVED** [review]
Ok. solved.

**Review by silvershiny — APPROVED** [review]
Awesome

**Review by goldsunshines — APPROVED** [review]
Very good idea

**Review by popstar7 — APPROVED** [review]
That is your Big effort

**Review by techietrend — APPROVED** [review]
Ok, approved

**Review by techietrend — APPROVED** [review]
Good job

**Review by BeautifulMoon211 — COMMENTED** [review]
🤩

**Pull request merged**
